// 'use client'
// Global styles
import '../../public/static/style.css'

import { Inter } from 'next/font/google'

import StyledComponentsRegistry from '../../lib/registry'

const inter = Inter({ subsets: ['latin'] })

import AppContext from './context'

// Context
// import { createContext } from 'react'
// const AdminSettingsContext = createContext()

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

async function getData () {
  const res = await fetch('https://queenballers.club/api/admin')

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data')
  }

  return res.json()
}

export default async function RootLayout ({ children }) {
  const adminSettings = await getData()

  console.log(adminSettings)

  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppContext adminSettings={adminSettings}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </AppContext>
      </body>
    </html>
  )
}
